---
title: "Final report - Exploratory Data analysis"
subtitle: '2030071 - 1753320'
author: "Group 50: Romée Simons and Tycho Brouwer"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: cosmo
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    number_sections: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(psych)
library(kableExtra)
library(reprores)
library(ggpubr)
library(ggcorrplot)
library(plotly)
```

# Part 1 - Exploring the data
## 1 Inspecting the summary statistics

```{r, step 1a}
data_Sleep_Fatigue_AlcoholUse <- read_csv('df_Sleep_Fatigue_AlcoholUse.csv', show_col_types = FALSE) 

summary(data_Sleep_Fatigue_AlcoholUse)

```

```{r, 1b}
filtered_data <- data.frame( 'Trait self-control' = data_Sleep_Fatigue_AlcoholUse$TSC,
                            'Concentration (CIS)' = data_Sleep_Fatigue_AlcoholUse$CIS_Concentration, 
                            'Disturbances in sleep quality (PSQI)' = data_Sleep_Fatigue_AlcoholUse$PSQI_GlobalScore, 
                            'Chronotype (MCTQ)' = data_Sleep_Fatigue_AlcoholUse$MCTQ_MSFsc, 
                            'Alcohol usage (AUDIT)' =  data_Sleep_Fatigue_AlcoholUse$AUDIT_Score)

colnames(filtered_data) <- c('Trait self-control', 'Concentration (CIS)', 'Disturbances in sleep quality (PSQI)', 'Chronotype (MCTQ)', 'Alcohol usage (AUDIT)')

description_filtered_data <- filtered_data  %>%
  describe(fast = TRUE)

shown_columns <- c('n', 'mean', 'sd', 'min', 'max')
description_filtered_data <- description_filtered_data[shown_columns]

colnames(description_filtered_data) <- c('*n*', '*mean*', '*sd*', '*min*', '*max*')

kable(description_filtered_data,
      digits = 2,
      caption = 'Table 1. Descriptive Statistics') |>
  kable_classic() |>
  kable_styling(full_width = FALSE, font_size = 20)
```

## 2 Inspecting the variance

```{r, step 2}
create_hist <- function(x, data, label, fill_color, min_value, max_value) {
  plot <- ggplot(data, aes(x = .data[[x]])) + 
    geom_histogram(fill=fill_color, bins=10) +
    xlim(min_value, max_value) +
    xlab(label) + 
    ylab('Frequency')
  return(plot)
}

filtered_data <- na.omit(filtered_data)

plots_step_2 = list()
for (column in colnames(filtered_data)) {
  newplot = create_hist(column, filtered_data, column, "red", min(filtered_data[column]), max(filtered_data[column]))
  plots_step_2 <- append(plots_step_2, list(newplot))
}

figure1 <- ggarrange(plotlist = plots_step_2)

print(figure1)

```

## 3 Inspecting the central tendency

```{r}
#we need to use the lowerbound for the graph, because it is lower than the minimum value
sd_2 <- sd(filtered_data[[1]])*2
mean <- mean(filtered_data[[1]])
lowerbound <- (mean - sd_2)
upperbound <- (mean + sd_2)

figure2 <- create_hist('Trait self-control', filtered_data, 'Trait self-control', 'red', lowerbound, max(filtered_data[[1]])) +
  geom_vline(xintercept = mean(filtered_data[[1]]), color = 'black') +
  ggtitle('Figure 2')
```

```{r}
mean_rounded <- round(mean(filtered_data[[1]]),2)

figure3 <- figure2 +
  annotate('text', label = paste('mean = ', mean_rounded), x = 3.10, y = 21) +
  ggtitle('Figure 3')

print(figure3)
```

## 4 Detecting potential outliers

```{r}

outliers <- data_Sleep_Fatigue_AlcoholUse %>%
  filter(TSC > upperbound | TSC < lowerbound)

ID_outliers <- outliers$ID


if (length(ID_outliers)<1){
  print('There are no outliers')
  print(paste('The maximum is',max(filtered_data[[1]])))
  print(paste('The minimum is', min(filtered_data[[1]])))
} else {
  print(paste('outlier:', ID_outliers))
}

```

```{r}
figure4 <- 
  figure3 +
  geom_vline(xintercept = upperbound) +
  geom_vline(xintercept = lowerbound) +
  ggtitle('Figure 4')

print(figure4)
```

```{r echo=TRUE}
figure5 <- ggplotly(figure4)
  # + ggtitle('Figure 5')

figure5
```

```{r}
figure6 <- ggplot() +
  geom_boxplot(aes(data_Sleep_Fatigue_AlcoholUse$TSC))+
  xlab('Trait self-control') +
  ylab('frequency') +
  ggtitle('Figure 6')

print(figure6)
```

## 5 Inspecting covariance

```{r}
corr <- cor(filtered_data)
figure7 <- ggcorrplot(corr, hc.order = TRUE, lab = TRUE)

print(figure7)

```











