---
title: "Dashboard 0HV130"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(psych)
library(kableExtra)
library(reprores)
library(plotly)
library(DT)
```

```{r}
data_Sleep_Fatigue_AlcoholUse <- read_csv('df_Sleep_Fatigue_AlcoholUse.csv', show_col_types = FALSE)

filtered_data <- data.frame('ID' = data_Sleep_Fatigue_AlcoholUse$ID,
                            'TSC' = data_Sleep_Fatigue_AlcoholUse$TSC,
                            'CIS_Concentration' = data_Sleep_Fatigue_AlcoholUse$CIS_Concentration,
                            'PSQI_GlobalScore' = data_Sleep_Fatigue_AlcoholUse$PSQI_GlobalScore,
                            'MCTQ_MSFsc' = data_Sleep_Fatigue_AlcoholUse$MCTQ_MSFsc,
                            'AUDIT_Score' =  data_Sleep_Fatigue_AlcoholUse$AUDIT_Score)
```

Tables {data-orientation=rows data-icon="fa-table"}
=====================================  

Row 
-------------------------------------

### Total number of participants

```{r}
nRows <- nrow(data_Sleep_Fatigue_AlcoholUse)
valueBox(nRows, icon = "fa-users")
```

### Total number of variables

```{r}
nColumns <- ncol(data_Sleep_Fatigue_AlcoholUse)
valueBox(nColumns, icon = "fa-database")
```

### Total number of missings

```{r}
missingValues <- sum(is.na(data_Sleep_Fatigue_AlcoholUse))
valueBox(missingValues, icon = "fa-trash-can", color = "warning")
```

Row {.tabset .tabset-fade}
-------------------------------------
   
### Descriptive statistics

```{r}

description_filtered_data = filtered_data[,!(names(filtered_data) == "ID")]
description_filtered_data <- description_filtered_data  %>%
  describe(fast = TRUE)

rownames(description_filtered_data) <- c('Trait self-control', 'Concentration (CIS)', 'Disturbances in sleep quality (PSQI)', 'Chronotype (MCTQ)', 'Alcohol usage (AUDIT)')

shown_columns <- c('n', 'mean', 'sd', 'min', 'max')
description_filtered_data <- description_filtered_data[shown_columns]

colnames(description_filtered_data) <- c('*n*', '*mean*', '*sd*', '*min*', '*max*')
kable(description_filtered_data,
      digits = 2,
      caption = 'Table 1. Descriptive Statistics') |>
  kable_classic(full_width = FALSE, position="float_left")
```
 
### Dataframe

```{r}
datatable(filtered_data)
```
   
Visualizations {data-orientation=rows  data-icon="fa-signal"}
=====================================     
   
Row {data-height=600}
-------------------------------------

### Chart 1

```{r}
```

Row {data-height=400}
-------------------------------------
   
### Chart 2

```{r}
```   
    
### Chart 3

```{r}
```
