---
title: "Assignment 6 - Functions and simulations"
subtitle: '2030071 - 1753320'
author: "Group 50: Romée Simons and Tycho Brouwer"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: cosmo
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    number_sections: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#the needed packages are: 
library(tidyverse)
library(faux)
library(ggplot2)

set.seed(9)
```

# Question 1
## Part 1
```{r}
  
simulate_normal <- function(sample_size){
  samples <- rnorm(sample_size, mean = 0, sd = 1)
  sample_mean <- mean(samples)
  diff <- abs(sample_mean)
  return(diff)
}
n <- seq(10, 1000, by = 5)
diff <- sapply(n, simulate_normal)
Q1_1 <- data.frame(col1 = n, 
                   col2 = diff)

scatterplot <- ggplot() + 
  geom_point(aes(x = Q1_1$col1, y = Q1_1$col2), color = 'blue', alpha = 0.5) +
  geom_hline(yintercept = 0, color = 'red') +
  labs(x = 'Sample size', y = 'Absolute difference', title = 'Correlation between sample size and absolute difference') 

print(scatterplot)

```

## Part 2
```{r}

diff_squared <- (Q1_1$col2)^2
  
scatterplot_2 <- ggplot() + 
  geom_point(aes(x = Q1_1$col1[1:39], y = diff_squared[1:39]), color = 'blue', alpha = 0.5) +
  geom_hline(yintercept = 0, color = 'red') +
  labs(x = 'Sample size', y = 'Absolute difference squared', title = 'Correlation between sample size and squared absolute difference')

print(scatterplot_2)

```

## Part 3
```{r}
simulate_normal2 <- function(sample_size) {
  diff <- replicate(1000, abs(mean(rnorm(sample_size, mean = 0, sd = 1))))
  diff_squared <- diff^2
  mean_diff_squared <- mean(diff_squared)
  return(mean_diff_squared)
}

n <- seq(10, 200, by = 5)
m_diff <- sapply(n, simulate_normal2)
Q1_2 <- data.frame(col1 = n, 
                   col2 = m_diff)

scatterplot_3 <- ggplot() +
  geom_point(aes(x = Q1_2$col1, y = Q1_2$col2), color = 'blue', alpha = 0.5) +
  geom_hline(yintercept = 0, color = 'red') +
  labs(x = 'Sample size', y = 'Mean of absolute difference squared', title = 'Correlation between sample size and mean absolute difference')

print(scatterplot_3)
```

# Question 2
## Part 1
```{r}
Q2_1 <- rpois(n = 100000, lambda = 1)

density_plot <- ggplot() + 
  geom_density(aes(Q2_1), color = 'blue', fill = 'lightblue', alpha = 0.5) +
  labs(x = 'Nr of observations', y = 'Density', title = 'Density plot of Poisson distribution')

Q2_2 <- rpois(n = 100000, lambda = 5)

density_plot2 <- ggplot() + 
  geom_density(aes(Q2_2), color = 'red', fill = 'salmon', alpha = 0.5) +
  labs(x = 'Nr of observations', y = 'Density', title = 'Density plot of Poisson distribution')

Q2_3 <- rpois(n = 100000, lambda = 15)

density_plot3 <- ggplot() +
  geom_density(aes(Q2_3), color = 'green', fill = 'palegreen', alpha = 0.5) +
  labs(x = 'Nr of observations', y = 'Density', title = 'Density plot of Poisson distribution')

Q2_4 <- rpois(n = 100000, lambda = 150)

density_plot4 <- ggplot() +
  geom_density(aes(Q2_4), color = 'purple', fill = 'magenta', alpha = 0.5) +
  labs(x = 'Nr of observations', y = 'Density', title = 'Density plot of Poisson distribution')

print(density_plot)
print(density_plot2)
print(density_plot3)
print(density_plot4)
```

## Part 2
```{r}
Q2_5 <- rbinom(n = 100000, size = 1, prob = 0.5)

density_plot <- ggplot() + 
  geom_density(aes(Q2_5), color = 'blue', fill = 'lightblue', alpha = 0.5) + 
  labs(x = 'Nr of observations', y = 'Density', title = 'Density plot of binomial distribution')

Q2_6 <- rbinom(n = 100000, size = 5, prob = 0.5)

density_plot2 <- ggplot() + 
  geom_density(aes(Q2_6), color = 'red', fill = 'salmon', alpha = 0.5) + 
  labs(x = 'Nr of observations', y = 'Density', title = 'Density plot of binomial distribution')

Q2_7 <- rbinom(n = 100000, size = 15, prob = 0.5)

density_plot3 <- ggplot() + 
  geom_density(aes(Q2_7), color = 'green', fill = 'palegreen', alpha = 0.5) + 
  labs(x = 'Nr of observations', y = 'Density', title = 'Density plot of binomial distribution')

Q2_8 <- rbinom(n = 100000, size = 150, prob = 0.5)

density_plot4 <- ggplot() + 
  geom_density(aes(Q2_8), color = 'purple', fill = 'magenta', alpha = 0.5) + 
  labs(x = 'Nr of observations', y = 'Density', title = 'Density plot of binomial distribution')

print(density_plot)
print(density_plot2)
print(density_plot3)
print(density_plot4)
```

# Question 3
## Part 1
```{r}
simulate_sample <- function(sample_size, l) {
  sample <- rpois(n = sample_size, lambda = l)
  mean <- mean(sample)
  return(mean)
}

Q3_1 <- replicate(100000, abs(simulate_sample(50,1)- simulate_sample(50,1)))
```

## Part 2
```{r}
Q3_2 <- quantile(Q3_1, c(0.025,0.975))
print(Q3_2)

density_plot <- ggplot() + 
  geom_density(aes(Q3_1), color= 'blue', fill = 'lightblue', alpha = 0.5) + 
  geom_vline(xintercept = Q3_2, color = 'red') +
  labs(x = 'Nr of observations', y = 'Density', title = 'Density plot with quantile lines')

#not sure if the plot is correct 

print(density_plot)
```

# Question 4
## Part 1
