---
title: "Assignment 5 - Data wrangling"
subtitle: '2030071 - 1753320'
author: "Group 50: Romée Simons and Tycho Brouwer"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: cosmo
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    number_sections: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#the needed packages are:
library(knitr)
library(kableExtra)
library(tidyverse)
library(readxl)

set.seed(30250) #makes sure random numbers are reproducible

```

# Task 1

```{r, load data}
data_raw <- read_xlsx("data.xlsx")

data_raw$education = as.factor(data_raw$education)
data_raw$urban = as.factor(data_raw$urban)
data_raw$gender = as.factor(data_raw$gender)
data_raw$engnat = as.factor(data_raw$engnat)
data_raw$hand = as.factor(data_raw$hand)
data_raw$religion = as.factor(data_raw$religion)
data_raw$orientation = as.factor(data_raw$orientation)
data_raw$race = as.factor(data_raw$race)
data_raw$voted = as.factor(data_raw$voted)
data_raw$married = as.factor(data_raw$married)
```


```{r, plot}
data_filtered = data_raw[!data_raw$VCL6 == 1, ]
data_filtered = data_raw[!data_raw$VCL9 == 1, ]
data_filtered = data_raw[!data_raw$VCL12 == 1, ]

data_filtered |>
  mutate(VCL = VCL1 + VCL2 + VCL3 + VCL4 + VCL5 + VCL6 + VCL7 + VCL8 + VCL9 + VCL10 + VCL11 + VCL12 + VCL13 + VCL14 + VCL15 + VCL16) |>
  mutate(`education level` = recode(education,
                                    "0" = "No answer",
                                    "1" = "Less than high school",
                                    "2" = "High school",
                                    "3" = "University degree",
                                    "4" = "Graduate degree" )) |>
  group_by(`education level`) |>
  summarise(
    `mean total VCL` = round(mean(VCL, na.rm = TRUE), 2),
    `std total VCL`  = round(sd(VCL, na.rm = TRUE), 2),
    `min total VCL`  = min(VCL, na.rm = TRUE),
    `max total VCL`  = max(VCL, na.rm = TRUE),
    .groups = "drop"
  ) |>
  knitr::kable() |>
  kable_styling()
```

## Task 2

```{r}
data_filtered |>
  mutate(Depression = Q3A + Q5A + Q10A + Q13A + Q16A + Q17A + Q21A + Q24A + Q26A + Q31A + Q34A + Q37A + Q38A + Q42A - 14) |>
  mutate(Anxiety = Q2A + Q4A + Q7A + Q9A + Q15A + Q19A + Q20A + Q23A + Q25A + Q28A + Q30A + Q36A + Q40A + Q41A - 14) |>
  mutate(Stress = Q1A + Q6A + Q8A + Q11A + Q12A + Q14A + Q18A + Q22A + Q27A + Q29A + Q32A + Q33A + Q35A + Q39A -14) |>
  filter(
    education == 2 & urban == 1 | education == 4 & urban == 3
  ) |>
  mutate(`education level` = recode(education,
                                    "0" = "No answer",
                                    "1" = "Less than high school",
                                    "2" = "High school",
                                    "3" = "University degree",
                                    "4" = "Graduate degree" )) |>
  mutate(`environment` = recode(urban,
                                "0" = "No answer",
                                "1" = "Rural (country side)",
                                "2" = "Suburban",
                                "3" = "Urban (town, city)" )) |>
  group_by(`education level`, `environment`) |>
  summarise(
    `mean depression score` = round(mean(Depression, na.rm = TRUE), 2),
    `mean anxiety score` = round(mean(Anxiety, na.rm = TRUE), 2),
    `mean stress score` = round(mean(Stress, na.rm = TRUE), 2),
    .groups = "drop"
  ) |>
  knitr::kable() |>
  kable_styling()
```

## Task 3

```{r}
r1<-str_detect(AD1$major, "gine")
r<-as.numeric(r1)
AD <- bind_cols(AD1, r)
```

```{r}
AD <-AD |> rename(engineer=...174)
```

```{r}
table(AD$hand)

summary(AD$hand)

AD$hand <- case_match(
  AD$hand,
  1 ~ 0,
  2 ~ 1,
  3 ~ 0,
  .default = NA
)
AD$engineer <- case_match(
  AD$engineer,
  0 ~ "other major",
  1 ~ "engineer",
  NA ~ "no major"
)

lefthand <- AD |>
  group_by(engineer) |>
  summarise(
    n = n(),
    avg_hand = mean(hand, na.rm = TRUE),
    .groups = "drop"
  )

kable(lefthand, 
      digits = 2, 
      col.names = c("engineer", "nr", "proportion"),
      caption = "A comparision of urban and rural graduates") |>
  kable_classic() |>
  kable_styling(full_width = FALSE, font_size = 20) 
```

## Task 4

```{r}
AD <- AD  %>% 
  mutate(total = introelapse+ testelapse +surveyelapse)

summ_total <- AD |>
  group_by(country) |>
  summarise(
    n = n(),
    avg_time = mean(total, na.rm = TRUE),
    .groups = "drop"
  )

summ_total <- summ_total |> filter(n>100)

summ_total <- summ_total |> filter(n>100&avg_time == max(avg_time))
#summ_total <- summ_total |> filter(avg_time == max(avg_time))
kable(summ_total)
```





